### ISSUE TITLE
Chapter order mangled

### ISSUE THREAD

**Issue by apetro** [jdlich/cas-docs#5]
In my local Ubuntu 11.10 environment, builds to HTML and PDF with (same) mangled order of chapters.

**Comment by apetro** [comment]
Here's the weird order:

Table of Contents

Configuration Management

Assumptions
Installing Maven 2
Setting up your local Maven-Overlay-using CAS project
Services Management

What’s a service?
Service Name and Description
Service URL
Theme Name
Enable/Disable
SSO Participant
Anonymous Access
Allowed to proxy
User attributes
Evaluation Order
In-Memory Services Registry
JPA Services Registry
Configuring URLs to the Services Management UI in cas.properties
Authorizing users to access the Services Management tool
URL to the Services Management UI
Using the Web-based services registry administrative UI
Planning

CAS Client Integration
Authentication
Attribute Release
Supporting Services
Features

Installation

Hardening

Acknowledgements

Architecture

CAS Server
CAS Clients
CAS Protocol
SAML
OpenID
Authentication
Principal
Security Policy
Ticket Registry
Login workflow
Introduction

Single Sign-On (SSO) Implementation
SSO Diagram
Integration
Authentication Providers
Authorization
Commercial Support Channels

**Comment by apetro** [comment]
Re-tested against latest master.  Still broken order.

**Comment by jdlich** [comment]
Fixed with https://github.com/jdlich/cas-docs/commit/07d51b89a4bbb0c19c65282422cbf816e4c9da29
